### ISSUE TITLE
Can't find serializer for Ember-data 1.13.4

### ISSUE THREAD

**Issue by ryrych** [emberjs/ember-data-fixture-adapter#10]
`Error while processing route: todos serializer.get is not a function TypeError: serializer.get is not a function`

Application Adapter:

```
import Adapter from 'ember-data-fixture-adapter';

export default Adapter.extend({
  shouldReloadRecord: function() {
    return true;
  },
  shouldReloadAll: function() {
    return true;
  }
});
```

**Comment by bmac** [comment]
Looks like this is related to https://github.com/emberjs/data/issues/3427

**Comment by thatikuntap** [comment]
getting below error after nom install ember-data-fixture-adapter'

Error while processing route: tools Could not find module `ember-data-fixture-adapter'` imported from `ember-application/models/tool` Error: Could not find module `ember-data-fixture-adapter'` imported from `ember-application/models/tool`

**Comment by jme783** [comment]
+1, is there a fix for this???

**Comment by rwjblue** [comment]
Sorry that you are running into issues, this repo / project is essentially deprecated and unmaintained. 

I'm closing this (so that I can archive the repo and make it clearer to folks that this shouldn't be used going forward)...
