### ISSUE TITLE
Installing help

### ISSUE THREAD

**Issue by jevanlingen** [emberjs/ember-data-fixture-adapter#11]
Lately I am busy with the update to Ember 1.13, Ember Data 1.13 etc. As we use fixtures in our app, I tried this addon.

After I installed it with `ember install ember-data-fixture-adapter` the deprecation warning did not go away. Are there extra steps I am missing (adding a js to the ember-cli-build for example)?

**Comment by fivetanley** [comment]
we released 1.13.0. I'm not sure of the status of this but if you're using Ember CLI and follow the instructions in the README I think you should be good to go.

**Comment by jevanlingen** [comment]
Thx for the update. I installed the new version, but still I got the same error...

**Comment by rwjblue** [comment]
Sorry that you are running into issues, this repo / project is essentially deprecated and unmaintained. 

I'm closing this (so that I can archive the repo and make it clearer to folks that this shouldn't be used going forward)...
