### ISSUE TITLE
ember-data-fixture-adapter & queryRecord

### ISSUE THREAD

**Issue by sun-ks** [emberjs/ember-data-fixture-adapter#13]
Hello. I use Ember : 2.2.0, Ember Data : 2.2.0 and ember-data-fixture-adapter last version. 
I have a model with a large many entries. How do I withdraw one entries, recording by id =1.
If i use <code>return this.store.queryRecord('video', { filter: { id: '1' } }).then(function(tomster) {

});</code> in my model, Console say - <pre>Error while processing route: video Assertion Failed: You tried to make a query but your adapter does not implement `queryRecord` Error: Assertion Failed: You tried to make a query but your adapter does not implement `queryRecord`</pre>
If use <code>return this.store.findAll('video'); </code> All records without errors. But I need one! where id =1    =)

For examle, my files:
adapters/application.js
<code>import DS from 'ember-data';
export { default } from 'ember-data-fixture-adapter';</code>

models/video.js
<code>import DS from 'ember-data';
var Video = DS.Model.extend({
  title: DS.attr('string'),
  num: DS.attr('string')
});
Video.reopenClass({
  FIXTURES: [
    {
      id: 1,
      num: '1',
      title: "Something something Basecamp1"
    },
    {
      id: 2,
      num: '2',
      title: "Something something Basecamp2"
    }
  ]
});
export default Video;</code>
routes/video.js
<code>
import Ember from 'ember';
export default Ember.Route.extend({
    model(params) {
        return this.store.queryRecord('video', { filter: { id: '1' } }).then(function(tomster) {
});
  }
});
</code>

**Comment by wecc** [comment]
Have you tried `store.findRecord('video', 1)`?

**Comment by sun-ks** [comment]
If use <code>return this.store.findRecord('video', 1);</code> console return <code>Uncaught TypeError: adapter.findRecord is not a function</code>

**Comment by bmac** [comment]
Looks like this repo hasn't been updated for Ember Data 2.0 yet. I'll open a pr.

**Comment by jme783** [comment]
@sun-ks +1 just ran into this

**Comment by stoman** [comment]
While learning a little Ember.js I also ran into this and found that the package at https://www.npmjs.com/package/ember-data-fixture-adapter is still using version 1.13.0 which does not include your commit ce93a14. Is it planned to update the package?

In the meantime I created the renamed functions from your commit with the following adapter:

```
import FixtureAdapter from 'ember-data-fixture-adapter';

export default FixtureAdapter.extend({
  findRecord(store, typeClass, id) {
    return this.find(store, typeClass, id);
  },

  query(store, typeClass, query) {
    return this.findQuery(store, typeClass, query);
  }
});
```

**Comment by rwjblue** [comment]
Sorry that you are running into issues, this repo / project is essentially deprecated and unmaintained. 

I'm closing this (so that I can archive the repo and make it clearer to folks that this shouldn't be used going forward)...
