### ISSUE TITLE
Need to wrap response

### ISSUE THREAD

**Issue by williamhector** [emberjs/ember-data-fixture-adapter#16]
I'm using Ember and Ember Data both 2.15.0, and I needed to wrap the response of the FixtureAdapter methods in order for them to be recognised by the calling method (from the Ember Data Store?) and processed into real Ember.Models. Eg:
```
// app/adapters/post.js
import FixtureAdapter from 'ember-data-fixture-adapter';
export default FixtureAdapter.extend({
	simulateRemoteResponse: false,
	findAll: function(){
		return this._super.apply(this, arguments).then(function(response){
			return { posts: response };
		});
	}
});
```
I'm using a RESTSerializer, if that matters, but I can't see how.

Is this intentional? Or perhaps caused by changes to Ember Data?
I'm currently upgrading from Ember 1.13 to 2.15.
The exact same fixtures and models worked fine in 1.13 using the built-in DS.FixtureAdapter, without needing to wrap the responses.

**Comment by rwjblue** [comment]
Sorry that you are running into issues, this repo / project is essentially deprecated and unmaintained. 

I'm closing this (so that I can archive the repo and make it clearer to folks that this shouldn't be used going forward)...
