### ISSUE TITLE
Would it be a good idea to prepare `giftwrap` version?

### ISSUE THREAD

**Issue by stefek99** [emberjs/ember-data-fixture-adapter#6]
We all know fixture-adapter no longer lives in Ember Data but in this repo.

https://github.com/emberjs/data/blob/master/CHANGELOG.md#breaking-changes

> You can use it as an addon, or build it using Ember Giftwrap.

https://github.com/ef4/ember-giftwrap#how 
- It's a 7 step process 
- This is a work-in-progress
- It's alpha quality
- Then it would require some hosting / CDN

---

Why is this important / relevant? To allow demos and tutorials use Fixture Adapter as previously...

**Comment by stefanpenner** [comment]
Ya it would be a good idea. Got time to push this forward?

**Comment by stefek99** [comment]
For my cases (demos / presentiations / tutorials / snippets) I started using ```jquery.mockjax``` as in here: http://emberjs.jsbin.com/hupiqihogu/1/edit?html,js,output

**Comment by rwjblue** [comment]
Sorry that you are running into issues, this repo / project is essentially deprecated and unmaintained. 

I'm closing this (so that I can archive the repo and make it clearer to folks that this shouldn't be used going forward)...
